spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  type-aliases-package: com.hydata.jwt_springboot_02.entity
  mapper-locations: classpath:mybatis/mapper/*Dao.xml
  config-location: classpath:mybatis/mybatis.xml